### PR TITLE
Added Linux (Ubuntu) portability and an "update tests dir" feature 

### PR DESCRIPTION
**Pull request by Dylan-Brotherston**
replaced the hard coded path with a generated one to allow portability

added a "-u" or "--update" argument that pulls all .jsons from the cse servers

*note*:
Please configure all the folders in your public_html exactly like lab02 because the program can download from it, i can also see you have a lab02x folder but it's not downloadable.

"--update" need tweaking as it requires both a class and a lab specified, when it should be alone, to run because i don't know how to use the Argument Parser. i tried for a while.

added a shell script to install the program 

both --update and installer only work on Ubuntu and cse, probably all Linux but i am unsure.

updated .gitignore to allow install.sh

updated the README with install instruction, probably needs proofreading.

also now that i think of it i should disable the update tests feature when the programs in your cse directory because it will try to download from itself into itself. Ill fix that

### CODE REVIEW

**Comment by Dylan-Brotherston** [comment]
The repository can no longer update itself from itself.

Fixed a bug where a error code return would update tests twice.

**Comment by Dylan-Brotherston** [comment]
How are args given ??
```json
"args":"arg1 ar2",
"args":["arg1","arg2"],
```

**Comment by galaharon** [comment]
Nice! I'll take a closer look when I get a chance - there are a few things I'd like to change however. 

If the user is using the script on a CSE system it should default to my user directory, so they don't need to update (less bloat on their file system + no need for unnecessary downloads), though it can be forced to use a local directory (--local flag maybe?) Otherwise I'd prefer the script attempt to update automatically based off versioning (or branch status) when run, with the --update flag being reserved to force an update. 

I'll fix the directory permissions, I set up that new one last night in a rush, whoops!

As for a move for an installation script, I'd prefer the tests be downloaded to a central folder so that it's more like a "true" installation (~/.local/lib/autotest maybe?)

**Comment by Dylan-Brotherston** [comment]
The install script currently installs to ~/otp/autotest. And the tests into ~/opt/autotest/tests so it keeps the file structure.

--update only updates the tests not the executable as ot would overwrite itself and do who knows what.

Defaulting to your directory is easy enough. Flags in shell scripts are not that easy so I'll see what i can do.

The script just uninstalls any autotest already there and installs itself. There are  no versions.

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by galaharon** [comment]
I didn't see that earlier - great! Is there a reason you're using wget and not the urllib or requests modules which would be platform agnostic? I don't care about progress bars or w/e

Also make sure all downloads are from the github repo and not the CSE servers.

**Comment by Dylan-Brotherston** [comment]
I am new to pyton and didnt know it had its own library.

_Sent from my Samsung SM-G930F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Dylan-Brotherston** [comment]
urllib can't download directories, it can only download files.

So the program needs to open the test/ dir as html, extract the sub dir names from the html to get the classes.

Then it then needs to do the same thing again with each class dirs html to extract the labs in each class.

And then it needs to read each lab dir html to find the file names.

Then finally downloading the files it finds:

all while tracking where it is to dynamically build a file location to download too.

**OR**

wget does that for us.

wget was never about the progress bar, it was automatic.

**Comment by galaharon** [comment]
You can download the git archive and extract that. I should have the basics of such a system done tonight 👍

**Comment by Dylan-Brotherston** [comment]
--update now uses zip of git repo and cleans folder after update.

install.sh will now link to source on CSE computers.

can be overwritten with "force".

**Comment by Dylan-Brotherston** [comment]
I see you have started to implement your update code.

This merge contains my working update code that doesn't require a hard coded path.

And it won't pull code into your public_html as that could cause a feedback loop

Nice work making --update run alone.

**Comment by galaharon** [comment]
I've decided to go with a different approach to this - the script will be getting a major overhaul this weekend once I get time.

**Pull request closed without merging**
